spring:
  application:
    name: Emp-Config-Server
  cloud:
    config: 
       server:
          git:
            uri: https://github.com/GirishKumar3763/cloud-config-server
            username: GirishKumar3763
            password: girish_007            
            skipSslValidation: true            
            clone-on-start: true   
            default_label: master        
                         
server:
  port: 8888  
  servlet:
    context-path: /empconfigserver
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
   serviceUrl:
    defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: false
  instance:
      preferIpAddress: true 
        
